package atom.tools.very.simple.generator.factory;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import javax.lang.model.element.Modifier;

import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.TypeSpec;

import atom.tools.very.simple.generator.mapper.JavaPoetWriter;

public class GeneratorFactory {

	private GeneratorClassFactory  clazzFactory;
	private File dirOutput = new File("GENERATED_COMPARATOR");
	private JavaPoetWriter javaPoetWritter;
	private static String packageName = "atom.generated.factory";
	private List<GeneratorClassFactory> listClassFactory = new ArrayList();
	final TypeSpec.Builder classBuilder;

	public GeneratorFactory(Class class1) throws ClassNotFoundException {
		this(class1,  TypeSpec.classBuilder(getClassFactoryName(class1)).addModifiers(Modifier.PUBLIC));
	}
	
	public GeneratorFactory(Class class1,TypeSpec.Builder classBuilder ) throws ClassNotFoundException {
		this.classBuilder = classBuilder;
		dirOutput.mkdirs();
		this.clazzFactory = new GeneratorClassFactory(class1);
		processClass(this.clazzFactory);

		javaPoetWritter = new JavaPoetWriter(dirOutput);
		javaPoetWritter.write(getJavaFileGenerator());
		System.err.println("ObjectFacrory Done  dirOutput exists  : " + dirOutput.exists() + " | path  : " + dirOutput.getAbsolutePath());
	}

	private void processClass(final GeneratorClassFactory c) throws ClassNotFoundException {

		listClassFactory.add(c);
		c.process();
		for (final Class cl : c.getListClass()) {
			if (!isProcessed(cl)) {
				processClass(new GeneratorClassFactory(cl));
			}
		}
	}

	private boolean isProcessed(Class  cp) {
		for (GeneratorClassFactory c : this.listClassFactory) {
			if (c.getClazz().equals(cp)) {
				return true;
			}
		}
		return false;
	}

	public JavaFile getJavaFileGenerator() {

	
		String comment = "Cette Class propose un factory utile pour les tests \n";
		comment += "Class : \t" + clazzFactory.getClazz().getName() + "\n";
	

	  
		comment += "\n\n ";
		classBuilder.addJavadoc(comment);
		classBuilder.addMethod(mainFactoryMethod());
	
		
		for (final GeneratorClassFactory cp : listClassFactory) {
			classBuilder.addMethod(cp.getMethodCreate());		
		}

		final TypeSpec customClassMapper = classBuilder.build();
		final JavaFile.Builder javaFileBuilder = JavaFile.builder(packageName, customClassMapper).indent("    ");

		javaFileBuilder.addFileComment("Generated by " + this.getClass().getName());
		final JavaFile javaFile = javaFileBuilder.build();
		return javaFile;
	}
	
	private static String getClassFactoryName(Class c) {
	
			return "Factory_" + c.getSimpleName();
	}
	
	private MethodSpec mainFactoryMethod( ) {
		final MethodSpec.Builder methodBuilder = MethodSpec.methodBuilder("createNewInstanceRandom").
			
				returns(clazzFactory.getClazz()).
				addModifiers(Modifier.PUBLIC).
				addModifiers(Modifier.STATIC);
		methodBuilder.addJavadoc("\nSeule methode public de la classe\n");
		
		methodBuilder.addStatement("return " + clazzFactory.getMethodName() + "()");
		return methodBuilder.build();
	}

}
